version: '3.7'
services:
  web_server:
    build:
      context: ./web_server
      dockerfile: Dockerfile
      args:
        - HOST_APP_DOMAIN=${HOST_APP_DOMAIN}
        - EXPORT_APP_HTTP_PORT=${EXPORT_APP_HTTP_PORT}
    image: ${DHUB_USER}/hp_nginx_web_srv:${WEB_SRV_IMG_VER}
    container_name: hp_nginx_web_srv_con
    environment:
      HOST_WEB_DOMAIN: ${HOST_WEB_DOMAIN}
      HOST_APP_DOMAIN: ${HOST_APP_DOMAIN}
      NAIVE_WEB_HTTP_PORT: ${NAIVE_WEB_HTTP_PORT}
      NAIVE_WEB_HTTPS_PORT: ${NAIVE_WEB_HTTPS_PORT}
      MAX_REQUEST_BODY_SIZE: ${MAX_REQUEST_BODY_SIZE}
    # depends_on:
    #   - app_server
    ports:
      - ${EXPORT_WEB_HTTP_PORT}:80
      - ${EXPORT_WEB_HTTPS_PORT}:443
    networks:
      - home_products_net
    volumes:
      # Binding
      - ./web_server/html:/usr/share/nginx/html
      - ./web_server/log/nginx.conf.log:/etc/nginx/nginx.conf

    # restart: unless-stopped


networks:
  home_products_net:
    driver: bridge

volumes:
  home_products_db:
    driver: local
      