#!/bin/sh

echo "[Check \$DJANGO_PROJECT_NAME] $DJANGO_PROJECT_NAME"
echo "[Check \$WSGI_UNIX_SOCKET_FILE] $WSGI_UNIX_SOCKET_FILE"
# exec gunicorn $DJANGO_PROJECT_NAME.wsgi --bind="unix:$WSGI_UNIX_SOCKET_FILE"

echo "[Check \$CONTAINER_WEB_DOMAIN] $CONTAINER_WEB_DOMAIN"
echo "[Ckeck \$CONTAINER_APP_HTTP_PORT] $CONTAINER_APP_HTTP_PORT"

# exec gunicorn $DJANGO_PROJECT_NAME.wsgi --bind="$HOST_WEB_DOMAIN:$NAIVE_WEB_HTTP_PORT"
exec gunicorn $DJANGO_PROJECT_NAME.wsgi --bind="0.0.0.0:$CONTAINER_APP_HTTP_PORT"